var searchData=
[
  ['fabmap',['FabMap',['../classcv_1_1of2_1_1_fab_map.html',1,'cv::of2']]],
  ['fabmap1',['FabMap1',['../classcv_1_1of2_1_1_fab_map1.html',1,'cv::of2']]],
  ['fabmap2',['FabMap2',['../classcv_1_1of2_1_1_fab_map2.html',1,'cv::of2']]],
  ['fabmapfbo',['FabMapFBO',['../classcv_1_1of2_1_1_fab_map_f_b_o.html',1,'cv::of2']]],
  ['fabmaplut',['FabMapLUT',['../classcv_1_1of2_1_1_fab_map_l_u_t.html',1,'cv::of2']]],
  ['facerecognitionexception',['FaceRecognitionException',['../class_face_recognition_g_u_i_1_1_face_recognition_task_1_1_face_recognition_exception.html',1,'FaceRecognitionGUI::FaceRecognitionTask']]],
  ['facerecognitiongui',['FaceRecognitionGUI',['../namespace_face_recognition_g_u_i.html',1,'']]],
  ['facerecognitiontask',['FaceRecognitionTask',['../class_face_recognition_g_u_i_1_1_face_recognition_task.html',1,'FaceRecognitionGUI']]],
  ['false',['False',['../classcvflann_1_1_false.html',1,'cvflann']]],
  ['farnebackopticalflow',['FarnebackOpticalFlow',['../classcv_1_1gpu_1_1_farneback_optical_flow.html',1,'cv::gpu']]],
  ['farnebackopticalflow',['FarnebackOpticalFlow',['../classcv_1_1ocl_1_1_farneback_optical_flow.html',1,'cv::ocl']]],
  ['fast_5fgpu',['FAST_GPU',['../classcv_1_1gpu_1_1_f_a_s_t___g_p_u.html',1,'cv::gpu']]],
  ['fastmarchingmethod',['FastMarchingMethod',['../classcv_1_1videostab_1_1_fast_marching_method.html',1,'cv::videostab']]],
  ['fastnonlocalmeansdenoising',['FastNonLocalMeansDenoising',['../classcv_1_1gpu_1_1_fast_non_local_means_denoising.html',1,'cv::gpu']]],
  ['fastopticalflowbm',['FastOpticalFlowBM',['../classcv_1_1gpu_1_1_fast_optical_flow_b_m.html',1,'cv::gpu']]],
  ['featherblender',['FeatherBlender',['../classcv_1_1detail_1_1_feather_blender.html',1,'cv::detail']]],
  ['feature',['Feature',['../class_feature.html',1,'']]],
  ['featuremap',['FeatureMap',['../class_feature_map.html',1,'']]],
  ['featuresfinder',['FeaturesFinder',['../classcv_1_1detail_1_1_features_finder.html',1,'cv::detail']]],
  ['featuresmatcher',['FeaturesMatcher',['../classcv_1_1detail_1_1_features_matcher.html',1,'cv::detail']]],
  ['fgdstatmodel',['FGDStatModel',['../classcv_1_1gpu_1_1_f_g_d_stat_model.html',1,'cv::gpu']]],
  ['filepath',['FilePath',['../classtesting_1_1internal_1_1_file_path.html',1,'testing::internal']]],
  ['filterengine_5fgpu',['FilterEngine_GPU',['../classcv_1_1gpu_1_1_filter_engine___g_p_u.html',1,'cv::gpu']]],
  ['filterengine_5fgpu',['FilterEngine_GPU',['../classcv_1_1ocl_1_1_filter_engine___g_p_u.html',1,'cv::ocl']]],
  ['filterimage',['filterImage',['../classhigh_pass_filter.html#a3b5c218bb45c78df3b03ecd9199ea079',1,'highPassFilter::filterImage()'],['../classlaplacian_filter.html#a36cdf1200291e90da6f30eb6a6bd3afb',1,'laplacianFilter::filterImage()']]],
  ['findneighbors',['findNeighbors',['../classcvflann_1_1_autotuned_index.html#a9cbf8f750d1f0df4db4c805b96103f3c',1,'cvflann::AutotunedIndex::findNeighbors()'],['../classcvflann_1_1_composite_index.html#a415d0daafd176f0f3a794281d3483c50',1,'cvflann::CompositeIndex::findNeighbors()'],['../classcvflann_1_1_index.html#a65866d94e0d29a5b9ffca22aba51e6b2',1,'cvflann::Index::findNeighbors()'],['../classcvflann_1_1_hierarchical_clustering_index.html#af25708c9cdeed93aeef8a533756832a8',1,'cvflann::HierarchicalClusteringIndex::findNeighbors()'],['../classcvflann_1_1_k_d_tree_index.html#ada91fb72025dec63ac669cfe36a1b66f',1,'cvflann::KDTreeIndex::findNeighbors()'],['../classcvflann_1_1_k_d_tree_single_index.html#aedd8818914111a3ef3740ee72c1b8477',1,'cvflann::KDTreeSingleIndex::findNeighbors()'],['../classcvflann_1_1_k_means_index.html#a2e666baa48e5094e755c0ccdeb908b55',1,'cvflann::KMeansIndex::findNeighbors()'],['../classcvflann_1_1_linear_index.html#ac2ac4c45a06c8c196e83edee9c343287',1,'cvflann::LinearIndex::findNeighbors()'],['../classcvflann_1_1_lsh_index.html#acde2974de8a4b2cfe72d849fdabddee9',1,'cvflann::LshIndex::findNeighbors()'],['../classcvflann_1_1_n_n_index.html#ac038c51dc941c7c1a55b08c17e213e41',1,'cvflann::NNIndex::findNeighbors()']]],
  ['fisheyeprojector',['FisheyeProjector',['../structcv_1_1detail_1_1_fisheye_projector.html',1,'cv::detail']]],
  ['fisheyewarper',['FisheyeWarper',['../classcv_1_1detail_1_1_fisheye_warper.html',1,'cv::detail']]],
  ['fisheyewarper',['FisheyeWarper',['../classcv_1_1_fisheye_warper.html',1,'cv']]],
  ['flags',['flags',['../classcv_1_1ocl_1_1ocl_mat.html#ae53eaacd0018d7b762a5c69c9a1d0d5f',1,'cv::ocl::oclMat']]],
  ['flannexception',['FLANNException',['../classcvflann_1_1_f_l_a_n_n_exception.html',1,'cvflann']]],
  ['floatingpoint',['FloatingPoint',['../classtesting_1_1internal_1_1_floating_point.html',1,'testing::internal']]],
  ['for',['For',['../structcv_1_1gpu_1_1device_1_1reduce__key__val__detail_1_1_for.html',1,'cv::gpu::device::reduce_key_val_detail']]],
  ['for',['For',['../structcv_1_1gpu_1_1device_1_1reduce__detail_1_1_for.html',1,'cv::gpu::device::reduce_detail']]],
  ['for_3c_20n_2c_20n_20_3e',['For&lt; N, N &gt;',['../structcv_1_1gpu_1_1device_1_1reduce__key__val__detail_1_1_for_3_01_n_00_01_n_01_4.html',1,'cv::gpu::device::reduce_key_val_detail']]],
  ['for_3c_20n_2c_20n_20_3e',['For&lt; N, N &gt;',['../structcv_1_1gpu_1_1device_1_1reduce__detail_1_1_for_3_01_n_00_01_n_01_4.html',1,'cv::gpu::device::reduce_detail']]],
  ['forceglob',['ForceGlob',['../structcv_1_1gpu_1_1device_1_1_force_glob.html',1,'cv::gpu::device']]],
  ['formatforcomparison',['FormatForComparison',['../classtesting_1_1internal_1_1_format_for_comparison.html',1,'testing::internal']]],
  ['formatforcomparison_3c_20toprint_5bn_5d_2c_20otheroperand_20_3e',['FormatForComparison&lt; ToPrint[N], OtherOperand &gt;',['../classtesting_1_1internal_1_1_format_for_comparison_3_01_to_print[_n]_00_01_other_operand_01_4.html',1,'testing::internal']]],
  ['formatinfo',['FormatInfo',['../structcv_1_1gpu_1_1_video_reader___g_p_u_1_1_format_info.html',1,'cv::gpu::VideoReader_GPU']]],
  ['framesource',['FrameSource',['../classcv_1_1superres_1_1_frame_source.html',1,'cv::superres']]],
  ['free',['free',['../classcvflann_1_1_matrix.html#a14b203d950b8496b269a66bf3c578eba',1,'cvflann::Matrix']]],
  ['free_5felements',['free_elements',['../classcvflann_1_1_hierarchical_clustering_index.html#a085dd40374648c92ea3a649ba80ac456',1,'cvflann::HierarchicalClusteringIndex']]],
  ['full',['full',['../classcvflann_1_1_unique_result_set.html#a6be2e327fabb1e4e62f08f9f746fd6ba',1,'cvflann::UniqueResultSet::full()'],['../classcvflann_1_1_radius_unique_result_set.html#a74a655e91b339927b458609a1d4e1eb4',1,'cvflann::RadiusUniqueResultSet::full()']]],
  ['properties',['Properties',['../namespace_face_recognition_g_u_i_1_1_properties.html',1,'FaceRecognitionGUI']]]
];
