var searchData=
[
  ['hamming',['Hamming',['../structcvflann_1_1_hamming.html',1,'cvflann']]],
  ['hamming',['Hamming',['../structcv_1_1ocl_1_1_hamming.html',1,'cv::ocl']]],
  ['hamming2',['Hamming2',['../structcvflann_1_1_hamming2.html',1,'cvflann']]],
  ['hammingdist',['HammingDist',['../structcv_1_1gpu_1_1device_1_1_hamming_dist.html',1,'cv::gpu::device']]],
  ['hamminglut',['HammingLUT',['../structcvflann_1_1_hamming_l_u_t.html',1,'cvflann']]],
  ['hamminglut2',['HammingLUT2',['../structcvflann_1_1_hamming_l_u_t2.html',1,'cvflann']]],
  ['hasnewfatalfailurehelper',['HasNewFatalFailureHelper',['../classtesting_1_1internal_1_1_has_new_fatal_failure_helper.html',1,'testing::internal']]],
  ['heap',['Heap',['../classcvflann_1_1_heap.html',1,'cvflann']]],
  ['hellingerdistance',['HellingerDistance',['../structcvflann_1_1_hellinger_distance.html',1,'cvflann']]],
  ['herebedragons',['HereBeDragons',['../class_here_be_dragons.html',1,'']]],
  ['hierarchicalclusteringindex',['HierarchicalClusteringIndex',['../classcvflann_1_1_hierarchical_clustering_index.html',1,'cvflann']]],
  ['hierarchicalclusteringindexparams',['HierarchicalClusteringIndexParams',['../structcvflann_1_1_hierarchical_clustering_index_params.html',1,'cvflann']]],
  ['highpassfilter',['highPassFilter',['../classhigh_pass_filter.html',1,'']]],
  ['histintersectiondistance',['HistIntersectionDistance',['../structcvflann_1_1_hist_intersection_distance.html',1,'cvflann']]],
  ['hls2rgb',['HLS2RGB',['../structcv_1_1gpu_1_1device_1_1color__detail_1_1_h_l_s2_r_g_b.html',1,'cv::gpu::device::color_detail']]],
  ['hls2rgb_3c_20uchar_2c_204_2c_204_2c_20bidx_2c_20hr_20_3e',['HLS2RGB&lt; uchar, 4, 4, bidx, hr &gt;',['../structcv_1_1gpu_1_1device_1_1color__detail_1_1_h_l_s2_r_g_b_3_01uchar_00_014_00_014_00_01bidx_00_01hr_01_4.html',1,'cv::gpu::device::color_detail']]],
  ['hogconfidence',['HOGConfidence',['../structcv_1_1gpu_1_1_h_o_g_confidence.html',1,'cv::gpu']]],
  ['hogdescriptor',['HOGDescriptor',['../structcv_1_1gpu_1_1_h_o_g_descriptor.html',1,'cv::gpu']]],
  ['hogdescriptor',['HOGDescriptor',['../structcv_1_1ocl_1_1_h_o_g_descriptor.html',1,'cv::ocl']]],
  ['homographybasedestimator',['HomographyBasedEstimator',['../classcv_1_1detail_1_1_homography_based_estimator.html',1,'cv::detail']]],
  ['houghcirclesbuf',['HoughCirclesBuf',['../structcv_1_1gpu_1_1_hough_circles_buf.html',1,'cv::gpu']]],
  ['houghlinesbuf',['HoughLinesBuf',['../structcv_1_1gpu_1_1_hough_lines_buf.html',1,'cv::gpu']]],
  ['hsv2rgb',['HSV2RGB',['../structcv_1_1gpu_1_1device_1_1color__detail_1_1_h_s_v2_r_g_b.html',1,'cv::gpu::device::color_detail']]],
  ['hsv2rgb_3c_20uchar_2c_204_2c_204_2c_20bidx_2c_20hr_20_3e',['HSV2RGB&lt; uchar, 4, 4, bidx, hr &gt;',['../structcv_1_1gpu_1_1device_1_1color__detail_1_1_h_s_v2_r_g_b_3_01uchar_00_014_00_014_00_01bidx_00_01hr_01_4.html',1,'cv::gpu::device::color_detail']]],
  ['hypot_5fsqr_5ffunc',['hypot_sqr_func',['../structcv_1_1gpu_1_1device_1_1hypot__sqr__func.html',1,'cv::gpu::device']]]
];
