var searchData=
[
  ['mainform',['MainForm',['../class_face_recognition_g_u_i_1_1_main_form.html',1,'FaceRecognitionGUI']]],
  ['maskcollection',['MaskCollection',['../structcv_1_1gpu_1_1device_1_1_mask_collection.html',1,'cv::gpu::device']]],
  ['matchesinfo',['MatchesInfo',['../structcv_1_1detail_1_1_matches_info.html',1,'cv::detail']]],
  ['matchtemplatebuf',['MatchTemplateBuf',['../structcv_1_1gpu_1_1_match_template_buf.html',1,'cv::gpu']]],
  ['matchtemplatebuf',['MatchTemplateBuf',['../structcv_1_1ocl_1_1_match_template_buf.html',1,'cv::ocl']]],
  ['matcomparator',['MatComparator',['../structcvtest_1_1_mat_comparator.html',1,'cvtest']]],
  ['matinfo',['MatInfo',['../structcvtest_1_1_mat_info.html',1,'cvtest']]],
  ['matrix',['Matrix',['../classcvflann_1_1_matrix.html',1,'cvflann']]],
  ['matrix_3c_20elementtype_20_3e',['Matrix&lt; ElementType &gt;',['../classcvflann_1_1_matrix.html',1,'cvflann']]],
  ['matrix_3c_20int_20_3e',['Matrix&lt; int &gt;',['../classcvflann_1_1_matrix.html',1,'cvflann']]],
  ['mattype',['MatType',['../classperf_1_1_mat_type.html',1,'perf']]],
  ['maxdistance',['MaxDistance',['../structcvflann_1_1_max_distance.html',1,'cvflann']]],
  ['maximum',['maximum',['../structcv_1_1gpu_1_1device_1_1maximum.html',1,'cv::gpu::device']]],
  ['mercatorprojector',['MercatorProjector',['../structcv_1_1detail_1_1_mercator_projector.html',1,'cv::detail']]],
  ['mercatorwarper',['MercatorWarper',['../classcv_1_1detail_1_1_mercator_warper.html',1,'cv::detail']]],
  ['mercatorwarper',['MercatorWarper',['../classcv_1_1_mercator_warper.html',1,'cv']]],
  ['message',['Message',['../classtesting_1_1_message.html',1,'testing']]],
  ['minimum',['minimum',['../structcv_1_1gpu_1_1device_1_1minimum.html',1,'cv::gpu::device']]],
  ['minkowskidistance',['MinkowskiDistance',['../structcvflann_1_1_minkowski_distance.html',1,'cvflann']]],
  ['minus',['minus',['../structcv_1_1gpu_1_1device_1_1minus.html',1,'cv::gpu::device']]],
  ['modulus',['modulus',['../structcv_1_1gpu_1_1device_1_1modulus.html',1,'cv::gpu::device']]],
  ['mog',['MOG',['../classcv_1_1ocl_1_1_m_o_g.html',1,'cv::ocl']]],
  ['mog2',['MOG2',['../classcv_1_1ocl_1_1_m_o_g2.html',1,'cv::ocl']]],
  ['mog2_5fgpu',['MOG2_GPU',['../classcv_1_1gpu_1_1_m_o_g2___g_p_u.html',1,'cv::gpu']]],
  ['mog_5fgpu',['MOG_GPU',['../classcv_1_1gpu_1_1_m_o_g___g_p_u.html',1,'cv::gpu']]],
  ['motionfilterbase',['MotionFilterBase',['../classcv_1_1videostab_1_1_motion_filter_base.html',1,'cv::videostab']]],
  ['motioninpainter',['MotionInpainter',['../classcv_1_1videostab_1_1_motion_inpainter.html',1,'cv::videostab']]],
  ['multibandblender',['MultiBandBlender',['../classcv_1_1detail_1_1_multi_band_blender.html',1,'cv::detail']]],
  ['multiplies',['multiplies',['../structcv_1_1gpu_1_1device_1_1multiplies.html',1,'cv::gpu::device']]],
  ['mutex',['Mutex',['../classtesting_1_1internal_1_1_mutex.html',1,'testing::internal']]]
];
