var searchData=
[
  ['datatype',['Datatype',['../structcvflann_1_1_datatype.html',1,'cvflann']]],
  ['datatype_3c_20char_20_3e',['Datatype&lt; char &gt;',['../structcvflann_1_1_datatype_3_01char_01_4.html',1,'cvflann']]],
  ['datatype_3c_20double_20_3e',['Datatype&lt; double &gt;',['../structcvflann_1_1_datatype_3_01double_01_4.html',1,'cvflann']]],
  ['datatype_3c_20float_20_3e',['Datatype&lt; float &gt;',['../structcvflann_1_1_datatype_3_01float_01_4.html',1,'cvflann']]],
  ['datatype_3c_20int_20_3e',['Datatype&lt; int &gt;',['../structcvflann_1_1_datatype_3_01int_01_4.html',1,'cvflann']]],
  ['datatype_3c_20short_20_3e',['Datatype&lt; short &gt;',['../structcvflann_1_1_datatype_3_01short_01_4.html',1,'cvflann']]],
  ['datatype_3c_20unsigned_20char_20_3e',['Datatype&lt; unsigned char &gt;',['../structcvflann_1_1_datatype_3_01unsigned_01char_01_4.html',1,'cvflann']]],
  ['datatype_3c_20unsigned_20int_20_3e',['Datatype&lt; unsigned int &gt;',['../structcvflann_1_1_datatype_3_01unsigned_01int_01_4.html',1,'cvflann']]],
  ['datatype_3c_20unsigned_20short_20_3e',['Datatype&lt; unsigned short &gt;',['../structcvflann_1_1_datatype_3_01unsigned_01short_01_4.html',1,'cvflann']]],
  ['deblurerbase',['DeblurerBase',['../classcv_1_1videostab_1_1_deblurer_base.html',1,'cv::videostab']]],
  ['defaultbinaryshift',['DefaultBinaryShift',['../structcv_1_1gpu_1_1device_1_1functional__detail_1_1_default_binary_shift.html',1,'cv::gpu::device::functional_detail']]],
  ['defaultextraction',['DefaultExtraction',['../class_default_extraction.html',1,'']]],
  ['defaultlocalization',['DefaultLocalization',['../class_default_localization.html',1,'']]],
  ['defaultpreprocessing',['DefaultPreProcessing',['../class_default_pre_processing.html',1,'']]],
  ['defaultrngauto',['DefaultRngAuto',['../structcvtest_1_1_default_rng_auto.html',1,'cvtest']]],
  ['defaulttransformfunctortraits',['DefaultTransformFunctorTraits',['../structcv_1_1gpu_1_1device_1_1_default_transform_functor_traits.html',1,'cv::gpu::device']]],
  ['defaulttransformshift',['DefaultTransformShift',['../structcv_1_1gpu_1_1device_1_1_default_transform_shift.html',1,'cv::gpu::device']]],
  ['defaultunaryshift',['DefaultUnaryShift',['../structcv_1_1gpu_1_1device_1_1functional__detail_1_1_default_unary_shift.html',1,'cv::gpu::device::functional_detail']]],
  ['denseopticalflowext',['DenseOpticalFlowExt',['../classcv_1_1superres_1_1_dense_optical_flow_ext.html',1,'cv::superres']]],
  ['deviceinfo',['DeviceInfo',['../structcv_1_1ocl_1_1_device_info.html',1,'cv::ocl']]],
  ['devicemanager',['DeviceManager',['../classcvtest_1_1_device_manager.html',1,'cvtest']]],
  ['disjointsets',['DisjointSets',['../classcv_1_1detail_1_1_disjoint_sets.html',1,'cv::detail']]],
  ['disparitybilateralfilter',['DisparityBilateralFilter',['../classcv_1_1gpu_1_1_disparity_bilateral_filter.html',1,'cv::gpu']]],
  ['dispatcher',['Dispatcher',['../structcv_1_1gpu_1_1device_1_1reduce__key__val__detail_1_1_dispatcher.html',1,'cv::gpu::device::reduce_key_val_detail']]],
  ['dispatcher',['Dispatcher',['../structcv_1_1gpu_1_1device_1_1reduce__detail_1_1_dispatcher.html',1,'cv::gpu::device::reduce_detail']]],
  ['distindex',['DistIndex',['../structcvflann_1_1_unique_result_set_1_1_dist_index.html',1,'cvflann::UniqueResultSet']]],
  ['divides',['divides',['../structcv_1_1gpu_1_1device_1_1divides.html',1,'cv::gpu::device']]],
  ['dllexecution',['DLLExecution',['../class_d_l_l_execution.html',1,'']]],
  ['double8',['double8',['../structcv_1_1gpu_1_1device_1_1double8.html',1,'cv::gpu::device']]],
  ['dpseamfinder',['DpSeamFinder',['../classcv_1_1detail_1_1_dp_seam_finder.html',1,'cv::detail']]],
  ['dynamicbitset',['DynamicBitset',['../classcvflann_1_1_dynamic_bitset.html',1,'cvflann']]],
  ['dynamicsharedmem',['DynamicSharedMem',['../structcv_1_1gpu_1_1device_1_1_dynamic_shared_mem.html',1,'cv::gpu::device']]],
  ['dynamicsharedmem_3c_20double_20_3e',['DynamicSharedMem&lt; double &gt;',['../structcv_1_1gpu_1_1device_1_1_dynamic_shared_mem_3_01double_01_4.html',1,'cv::gpu::device']]],
  ['dynamicthresholdfilter',['dynamicThresholdFilter',['../classdynamic_threshold_filter.html',1,'']]]
];
