var searchData=
[
  ['backgroundsubtractor',['BackgroundSubtractor',['../classcv_1_1_background_subtractor.html',1,'cv']]],
  ['backgroundsubtractor',['BackgroundSubtractor',['../classcv_1_1ocl_1_1_background_subtractor.html',1,'cv::ocl']]],
  ['backgroundsubtractorgmg',['BackgroundSubtractorGMG',['../classcv_1_1_background_subtractor_g_m_g.html',1,'cv']]],
  ['backgroundsubtractormog',['BackgroundSubtractorMOG',['../classcv_1_1_background_subtractor_m_o_g.html',1,'cv']]],
  ['backgroundsubtractormog2',['BackgroundSubtractorMOG2',['../classcv_1_1_background_subtractor_m_o_g2.html',1,'cv']]],
  ['bad_5fany_5fcast',['bad_any_cast',['../structcvflann_1_1anyimpl_1_1bad__any__cast.html',1,'cvflann::anyimpl']]],
  ['badargtest',['BadArgTest',['../classcvtest_1_1_bad_arg_test.html',1,'cvtest']]],
  ['base_5fany_5fpolicy',['base_any_policy',['../structcvflann_1_1anyimpl_1_1base__any__policy.html',1,'cvflann::anyimpl']]],
  ['basecolumnfilter_5fgpu',['BaseColumnFilter_GPU',['../classcv_1_1gpu_1_1_base_column_filter___g_p_u.html',1,'cv::gpu']]],
  ['basecolumnfilter_5fgpu',['BaseColumnFilter_GPU',['../classcv_1_1ocl_1_1_base_column_filter___g_p_u.html',1,'cv::ocl']]],
  ['basefilter_5fgpu',['BaseFilter_GPU',['../classcv_1_1gpu_1_1_base_filter___g_p_u.html',1,'cv::gpu']]],
  ['basefilter_5fgpu',['BaseFilter_GPU',['../classcv_1_1ocl_1_1_base_filter___g_p_u.html',1,'cv::ocl']]],
  ['baserowfilter_5fgpu',['BaseRowFilter_GPU',['../classcv_1_1gpu_1_1_base_row_filter___g_p_u.html',1,'cv::gpu']]],
  ['baserowfilter_5fgpu',['BaseRowFilter_GPU',['../classcv_1_1ocl_1_1_base_row_filter___g_p_u.html',1,'cv::ocl']]],
  ['basetest',['BaseTest',['../classcvtest_1_1_base_test.html',1,'cvtest']]],
  ['bestof2nearestmatcher',['BestOf2NearestMatcher',['../classcv_1_1detail_1_1_best_of2_nearest_matcher.html',1,'cv::detail']]],
  ['bfmatcher_5fgpu',['BFMatcher_GPU',['../classcv_1_1gpu_1_1_b_f_matcher___g_p_u.html',1,'cv::gpu']]],
  ['bfmatcher_5focl',['BFMatcher_OCL',['../classcv_1_1ocl_1_1_b_f_matcher___o_c_l.html',1,'cv::ocl']]],
  ['big_5fany_5fpolicy',['big_any_policy',['../structcvflann_1_1anyimpl_1_1big__any__policy.html',1,'cvflann::anyimpl']]],
  ['binary_5ffunction',['binary_function',['../structcv_1_1gpu_1_1device_1_1binary__function.html',1,'cv::gpu::device']]],
  ['binary_5ffunction_3c_20predicate_3a_3afirst_5fargument_5ftype_2c_20predicate_3a_3asecond_5fargument_5ftype_2c_20bool_20_3e',['binary_function&lt; Predicate::first_argument_type, Predicate::second_argument_type, bool &gt;',['../structcv_1_1gpu_1_1device_1_1binary__function.html',1,'cv::gpu::device']]],
  ['binary_5ffunction_3c_20t_2c_20t_2c_20bool_20_3e',['binary_function&lt; T, T, bool &gt;',['../structcv_1_1gpu_1_1device_1_1binary__function.html',1,'cv::gpu::device']]],
  ['binary_5ffunction_3c_20t_2c_20t_2c_20float_20_3e',['binary_function&lt; T, T, float &gt;',['../structcv_1_1gpu_1_1device_1_1binary__function.html',1,'cv::gpu::device']]],
  ['binary_5ffunction_3c_20t_2c_20t_2c_20t_20_3e',['binary_function&lt; T, T, T &gt;',['../structcv_1_1gpu_1_1device_1_1binary__function.html',1,'cv::gpu::device']]],
  ['binary_5ffunction_3c_20t1_2c_20t2_2c_20t1_20_3e',['binary_function&lt; T1, T2, T1 &gt;',['../structcv_1_1gpu_1_1device_1_1binary__function.html',1,'cv::gpu::device']]],
  ['binary_5ffunction_3c_20t1_2c_20t2_2c_20t2_20_3e',['binary_function&lt; T1, T2, T2 &gt;',['../structcv_1_1gpu_1_1device_1_1binary__function.html',1,'cv::gpu::device']]],
  ['binary_5fnegate',['binary_negate',['../structcv_1_1gpu_1_1device_1_1binary__negate.html',1,'cv::gpu::device']]],
  ['binaryreadwritetraits',['BinaryReadWriteTraits',['../structcv_1_1gpu_1_1device_1_1transform__detail_1_1_binary_read_write_traits.html',1,'cv::gpu::device::transform_detail']]],
  ['binder1st',['binder1st',['../structcv_1_1gpu_1_1device_1_1binder1st.html',1,'cv::gpu::device']]],
  ['binder2nd',['binder2nd',['../structcv_1_1gpu_1_1device_1_1binder2nd.html',1,'cv::gpu::device']]],
  ['binopshift',['BinOpShift',['../structcv_1_1gpu_1_1device_1_1functional__detail_1_1_bin_op_shift.html',1,'cv::gpu::device::functional_detail']]],
  ['binopshift_3c_20src_5felem_5fsize1_2c_20src_5felem_5fsize2_2c_201_20_3e',['BinOpShift&lt; src_elem_size1, src_elem_size2, 1 &gt;',['../structcv_1_1gpu_1_1device_1_1functional__detail_1_1_bin_op_shift_3_01src__elem__size1_00_01src__elem__size2_00_011_01_4.html',1,'cv::gpu::device::functional_detail']]],
  ['binopshift_3c_20src_5felem_5fsize1_2c_20src_5felem_5fsize2_2c_202_20_3e',['BinOpShift&lt; src_elem_size1, src_elem_size2, 2 &gt;',['../structcv_1_1gpu_1_1device_1_1functional__detail_1_1_bin_op_shift_3_01src__elem__size1_00_01src__elem__size2_00_012_01_4.html',1,'cv::gpu::device::functional_detail']]],
  ['bit_5fand',['bit_and',['../structcv_1_1gpu_1_1device_1_1bit__and.html',1,'cv::gpu::device']]],
  ['bit_5fnot',['bit_not',['../structcv_1_1gpu_1_1device_1_1bit__not.html',1,'cv::gpu::device']]],
  ['bit_5for',['bit_or',['../structcv_1_1gpu_1_1device_1_1bit__or.html',1,'cv::gpu::device']]],
  ['bit_5fxor',['bit_xor',['../structcv_1_1gpu_1_1device_1_1bit__xor.html',1,'cv::gpu::device']]],
  ['blender',['Blender',['../classcv_1_1detail_1_1_blender.html',1,'cv::detail']]],
  ['block',['Block',['../structcv_1_1gpu_1_1device_1_1_block.html',1,'cv::gpu::device']]],
  ['blockscan',['BlockScan',['../structcv_1_1gpu_1_1device_1_1_block_scan.html',1,'cv::gpu::device']]],
  ['blocksgaincompensator',['BlocksGainCompensator',['../classcv_1_1detail_1_1_blocks_gain_compensator.html',1,'cv::detail']]],
  ['bool_5fconstant',['bool_constant',['../structtesting_1_1internal_1_1bool__constant.html',1,'testing::internal']]],
  ['bool_5fconstant_3c_20implicitlyconvertible_3c_20const_20t_20_2a_2c_20const_20_3a_3aprotocolmessage_20_2a_20_3e_3a_3avalue_7c_7cimplicitlyconvertible_3c_20const_20t_20_2a_2c_20const_20_3a_3aproto2_3a_3amessage_20_2a_20_3e_3a_3avalue_20_3e',['bool_constant&lt; ImplicitlyConvertible&lt; const T *, const ::ProtocolMessage * &gt;::value||ImplicitlyConvertible&lt; const T *, const ::proto2::Message * &gt;::value &gt;',['../structtesting_1_1internal_1_1bool__constant.html',1,'testing::internal']]],
  ['borderreader',['BorderReader',['../structcv_1_1gpu_1_1device_1_1_border_reader.html',1,'cv::gpu::device']]],
  ['borderreader_3c_20ptr2d_2c_20brdconstant_3c_20d_20_3e_20_3e',['BorderReader&lt; Ptr2D, BrdConstant&lt; D &gt; &gt;',['../structcv_1_1gpu_1_1device_1_1_border_reader_3_01_ptr2_d_00_01_brd_constant_3_01_d_01_4_01_4.html',1,'cv::gpu::device']]],
  ['bowmsctrainer',['BOWMSCTrainer',['../classcv_1_1of2_1_1_b_o_w_m_s_c_trainer.html',1,'cv::of2']]],
  ['branchstruct',['BranchStruct',['../structcvflann_1_1_branch_struct.html',1,'cvflann']]],
  ['brdcolconstant',['BrdColConstant',['../structcv_1_1gpu_1_1device_1_1_brd_col_constant.html',1,'cv::gpu::device']]],
  ['brdcolreflect',['BrdColReflect',['../structcv_1_1gpu_1_1device_1_1_brd_col_reflect.html',1,'cv::gpu::device']]],
  ['brdcolreflect101',['BrdColReflect101',['../structcv_1_1gpu_1_1device_1_1_brd_col_reflect101.html',1,'cv::gpu::device']]],
  ['brdcolreplicate',['BrdColReplicate',['../structcv_1_1gpu_1_1device_1_1_brd_col_replicate.html',1,'cv::gpu::device']]],
  ['brdcolwrap',['BrdColWrap',['../structcv_1_1gpu_1_1device_1_1_brd_col_wrap.html',1,'cv::gpu::device']]],
  ['brdconstant',['BrdConstant',['../structcv_1_1gpu_1_1device_1_1_brd_constant.html',1,'cv::gpu::device']]],
  ['brdreflect',['BrdReflect',['../structcv_1_1gpu_1_1device_1_1_brd_reflect.html',1,'cv::gpu::device']]],
  ['brdreflect101',['BrdReflect101',['../structcv_1_1gpu_1_1device_1_1_brd_reflect101.html',1,'cv::gpu::device']]],
  ['brdreplicate',['BrdReplicate',['../structcv_1_1gpu_1_1device_1_1_brd_replicate.html',1,'cv::gpu::device']]],
  ['brdrowconstant',['BrdRowConstant',['../structcv_1_1gpu_1_1device_1_1_brd_row_constant.html',1,'cv::gpu::device']]],
  ['brdrowreflect',['BrdRowReflect',['../structcv_1_1gpu_1_1device_1_1_brd_row_reflect.html',1,'cv::gpu::device']]],
  ['brdrowreflect101',['BrdRowReflect101',['../structcv_1_1gpu_1_1device_1_1_brd_row_reflect101.html',1,'cv::gpu::device']]],
  ['brdrowreplicate',['BrdRowReplicate',['../structcv_1_1gpu_1_1device_1_1_brd_row_replicate.html',1,'cv::gpu::device']]],
  ['brdrowwrap',['BrdRowWrap',['../structcv_1_1gpu_1_1device_1_1_brd_row_wrap.html',1,'cv::gpu::device']]],
  ['brdwrap',['BrdWrap',['../structcv_1_1gpu_1_1device_1_1_brd_wrap.html',1,'cv::gpu::device']]],
  ['broxopticalflow',['BroxOpticalFlow',['../classcv_1_1gpu_1_1_brox_optical_flow.html',1,'cv::gpu']]],
  ['bruteforcematcher_5fgpu_3c_20hamming_20_3e',['BruteForceMatcher_GPU&lt; Hamming &gt;',['../classcv_1_1gpu_1_1_brute_force_matcher___g_p_u_3_01_hamming_01_4.html',1,'cv::gpu']]],
  ['bruteforcematcher_5fgpu_3c_20l1_3c_20t_20_3e_20_3e',['BruteForceMatcher_GPU&lt; L1&lt; T &gt; &gt;',['../classcv_1_1gpu_1_1_brute_force_matcher___g_p_u_3_01_l1_3_01_t_01_4_01_4.html',1,'cv::gpu']]],
  ['bruteforcematcher_5fgpu_3c_20l2_3c_20t_20_3e_20_3e',['BruteForceMatcher_GPU&lt; L2&lt; T &gt; &gt;',['../classcv_1_1gpu_1_1_brute_force_matcher___g_p_u_3_01_l2_3_01_t_01_4_01_4.html',1,'cv::gpu']]],
  ['bruteforcematcher_5fgpu_5fbase',['BruteForceMatcher_GPU_base',['../classcv_1_1gpu_1_1_brute_force_matcher___g_p_u__base.html',1,'cv::gpu']]],
  ['bruteforcematcher_5focl_3c_20hamming_20_3e',['BruteForceMatcher_OCL&lt; Hamming &gt;',['../classcv_1_1ocl_1_1_brute_force_matcher___o_c_l_3_01_hamming_01_4.html',1,'cv::ocl']]],
  ['bruteforcematcher_5focl_3c_20l1_3c_20t_20_3e_20_3e',['BruteForceMatcher_OCL&lt; L1&lt; T &gt; &gt;',['../classcv_1_1ocl_1_1_brute_force_matcher___o_c_l_3_01_l1_3_01_t_01_4_01_4.html',1,'cv::ocl']]],
  ['bruteforcematcher_5focl_3c_20l2_3c_20t_20_3e_20_3e',['BruteForceMatcher_OCL&lt; L2&lt; T &gt; &gt;',['../classcv_1_1ocl_1_1_brute_force_matcher___o_c_l_3_01_l2_3_01_t_01_4_01_4.html',1,'cv::ocl']]],
  ['bruteforcematcher_5focl_5fbase',['BruteForceMatcher_OCL_base',['../classcv_1_1ocl_1_1_brute_force_matcher___o_c_l__base.html',1,'cv::ocl']]],
  ['bundleadjusterbase',['BundleAdjusterBase',['../classcv_1_1detail_1_1_bundle_adjuster_base.html',1,'cv::detail']]],
  ['bundleadjusterray',['BundleAdjusterRay',['../classcv_1_1detail_1_1_bundle_adjuster_ray.html',1,'cv::detail']]],
  ['bundleadjusterreproj',['BundleAdjusterReproj',['../classcv_1_1detail_1_1_bundle_adjuster_reproj.html',1,'cv::detail']]],
  ['byref',['ByRef',['../structstd_1_1tr1_1_1gtest__internal_1_1_by_ref.html',1,'std::tr1::gtest_internal']]],
  ['byref_3c_20t_20_26_20_3e',['ByRef&lt; T &amp; &gt;',['../structstd_1_1tr1_1_1gtest__internal_1_1_by_ref_3_01_t_01_6_01_4.html',1,'std::tr1::gtest_internal']]]
];
