var searchData=
[
  ['samesizetupleprefixcomparator',['SameSizeTuplePrefixComparator',['../structstd_1_1tr1_1_1gtest__internal_1_1_same_size_tuple_prefix_comparator.html',1,'std::tr1::gtest_internal']]],
  ['samesizetupleprefixcomparator_3c_200_2c_200_20_3e',['SameSizeTuplePrefixComparator&lt; 0, 0 &gt;',['../structstd_1_1tr1_1_1gtest__internal_1_1_same_size_tuple_prefix_comparator_3_010_00_010_01_4.html',1,'std::tr1::gtest_internal']]],
  ['samesizetupleprefixcomparator_3c_20k_2c_20k_20_3e',['SameSizeTuplePrefixComparator&lt; k, k &gt;',['../structstd_1_1tr1_1_1gtest__internal_1_1_same_size_tuple_prefix_comparator_3_01k_00_01k_01_4.html',1,'std::tr1::gtest_internal']]],
  ['satcasthelper',['SatCastHelper',['../structcv_1_1gpu_1_1device_1_1vec__math__detail_1_1_sat_cast_helper.html',1,'cv::gpu::device::vec_math_detail']]],
  ['satcasthelper_3c_201_2c_20vecd_20_3e',['SatCastHelper&lt; 1, VecD &gt;',['../structcv_1_1gpu_1_1device_1_1vec__math__detail_1_1_sat_cast_helper_3_011_00_01_vec_d_01_4.html',1,'cv::gpu::device::vec_math_detail']]],
  ['satcasthelper_3c_202_2c_20vecd_20_3e',['SatCastHelper&lt; 2, VecD &gt;',['../structcv_1_1gpu_1_1device_1_1vec__math__detail_1_1_sat_cast_helper_3_012_00_01_vec_d_01_4.html',1,'cv::gpu::device::vec_math_detail']]],
  ['satcasthelper_3c_203_2c_20vecd_20_3e',['SatCastHelper&lt; 3, VecD &gt;',['../structcv_1_1gpu_1_1device_1_1vec__math__detail_1_1_sat_cast_helper_3_013_00_01_vec_d_01_4.html',1,'cv::gpu::device::vec_math_detail']]],
  ['satcasthelper_3c_204_2c_20vecd_20_3e',['SatCastHelper&lt; 4, VecD &gt;',['../structcv_1_1gpu_1_1device_1_1vec__math__detail_1_1_sat_cast_helper_3_014_00_01_vec_d_01_4.html',1,'cv::gpu::device::vec_math_detail']]],
  ['saturate_5fcast_5ffunc',['saturate_cast_func',['../structcv_1_1gpu_1_1device_1_1saturate__cast__func.html',1,'cv::gpu::device']]],
  ['savedindexparams',['SavedIndexParams',['../structcvflann_1_1_saved_index_params.html',1,'cvflann']]],
  ['scoped_5fptr',['scoped_ptr',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20_3a_3astd_3a_3astring_20_3e',['scoped_ptr&lt; ::std::string &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20_3a_3astd_3a_3astringstream_20_3e',['scoped_ptr&lt; ::std::stringstream &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20const_20_3a_3astd_3a_3astring_20_3e',['scoped_ptr&lt; const ::std::string &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20const_20t_20_3e',['scoped_ptr&lt; const T &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20testing_3a_3ainternal_3a_3aparamiteratorinterface_3c_20t_20_3e_20_3e',['scoped_ptr&lt; testing::internal::ParamIteratorInterface&lt; T &gt; &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20testing_3a_3ainternal_3a_3atestmetafactorybase_3c_20paramtype_20_3e_20_3e',['scoped_ptr&lt; testing::internal::TestMetaFactoryBase&lt; ParamType &gt; &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scopedtrace',['ScopedTrace',['../classtesting_1_1internal_1_1_scoped_trace.html',1,'testing::internal']]],
  ['seamfinder',['SeamFinder',['../classcv_1_1detail_1_1_seam_finder.html',1,'cv::detail']]],
  ['searchparams',['SearchParams',['../structcvflann_1_1_search_params.html',1,'cvflann']]],
  ['select',['Select',['../structcv_1_1gpu_1_1device_1_1type__traits__detail_1_1_select.html',1,'cv::gpu::device::type_traits_detail']]],
  ['select_3c_20false_2c_20t1_2c_20t2_20_3e',['Select&lt; false, T1, T2 &gt;',['../structcv_1_1gpu_1_1device_1_1type__traits__detail_1_1_select_3_01false_00_01_t1_00_01_t2_01_4.html',1,'cv::gpu::device::type_traits_detail']]],
  ['shiftdispatcher',['ShiftDispatcher',['../structcv_1_1gpu_1_1device_1_1functional__detail_1_1_shift_dispatcher.html',1,'cv::gpu::device::functional_detail']]],
  ['shiftdispatcher_3c_20func_2c_20false_20_3e',['ShiftDispatcher&lt; Func, false &gt;',['../structcv_1_1gpu_1_1device_1_1functional__detail_1_1_shift_dispatcher_3_01_func_00_01false_01_4.html',1,'cv::gpu::device::functional_detail']]],
  ['shiftdispatcher_3c_20func_2c_20true_20_3e',['ShiftDispatcher&lt; Func, true &gt;',['../structcv_1_1gpu_1_1device_1_1functional__detail_1_1_shift_dispatcher_3_01_func_00_01true_01_4.html',1,'cv::gpu::device::functional_detail']]],
  ['simpledistance',['simpleDistance',['../structcvflann_1_1simple_distance.html',1,'cvflann']]],
  ['simpledistance_3c_20chisquaredistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['simpleDistance&lt; ChiSquareDistance&lt; ElementType &gt;, ElementType &gt;',['../structcvflann_1_1simple_distance_3_01_chi_square_distance_3_01_element_type_01_4_00_01_element_type_01_4.html',1,'cvflann']]],
  ['simpledistance_3c_20hellingerdistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['simpleDistance&lt; HellingerDistance&lt; ElementType &gt;, ElementType &gt;',['../structcvflann_1_1simple_distance_3_01_hellinger_distance_3_01_element_type_01_4_00_01_element_type_01_4.html',1,'cvflann']]],
  ['simpledistance_3c_20l2_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['simpleDistance&lt; L2&lt; ElementType &gt;, ElementType &gt;',['../structcvflann_1_1simple_distance_3_01_l2_3_01_element_type_01_4_00_01_element_type_01_4.html',1,'cvflann']]],
  ['simpledistance_3c_20l2_5fsimple_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['simpleDistance&lt; L2_Simple&lt; ElementType &gt;, ElementType &gt;',['../structcvflann_1_1simple_distance_3_01_l2___simple_3_01_element_type_01_4_00_01_element_type_01_4.html',1,'cvflann']]],
  ['simpledistance_3c_20minkowskidistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['simpleDistance&lt; MinkowskiDistance&lt; ElementType &gt;, ElementType &gt;',['../structcvflann_1_1simple_distance_3_01_minkowski_distance_3_01_element_type_01_4_00_01_element_type_01_4.html',1,'cvflann']]],
  ['singlemask',['SingleMask',['../structcv_1_1gpu_1_1device_1_1_single_mask.html',1,'cv::gpu::device']]],
  ['singlemaskchannels',['SingleMaskChannels',['../structcv_1_1gpu_1_1device_1_1_single_mask_channels.html',1,'cv::gpu::device']]],
  ['small_5fany_5fpolicy',['small_any_policy',['../structcvflann_1_1anyimpl_1_1small__any__policy.html',1,'cvflann::anyimpl']]],
  ['smem',['smem',['../structcv_1_1gpu_1_1device_1_1_emulation_1_1smem.html',1,'cv::gpu::device::Emulation']]],
  ['sonnetxviii',['SonnetXVIII',['../class_sonnet_x_v_i_i_i.html',1,'']]],
  ['sparsepyrlkoptflowestimator',['SparsePyrLkOptFlowEstimator',['../classcv_1_1videostab_1_1_sparse_pyr_lk_opt_flow_estimator.html',1,'cv::videostab']]],
  ['sphericalportraitprojector',['SphericalPortraitProjector',['../structcv_1_1detail_1_1_spherical_portrait_projector.html',1,'cv::detail']]],
  ['sphericalportraitwarper',['SphericalPortraitWarper',['../classcv_1_1detail_1_1_spherical_portrait_warper.html',1,'cv::detail']]],
  ['sphericalprojector',['SphericalProjector',['../structcv_1_1detail_1_1_spherical_projector.html',1,'cv::detail']]],
  ['sphericalwarper',['SphericalWarper',['../classcv_1_1detail_1_1_spherical_warper.html',1,'cv::detail']]],
  ['sphericalwarper',['SphericalWarper',['../classcv_1_1_spherical_warper.html',1,'cv']]],
  ['sphericalwarpergpu',['SphericalWarperGpu',['../classcv_1_1detail_1_1_spherical_warper_gpu.html',1,'cv::detail']]],
  ['sphericalwarpergpu',['SphericalWarperGpu',['../classcv_1_1_spherical_warper_gpu.html',1,'cv']]],
  ['squaredistance',['squareDistance',['../structcvflann_1_1square_distance.html',1,'cvflann']]],
  ['squaredistance_3c_20chisquaredistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['squareDistance&lt; ChiSquareDistance&lt; ElementType &gt;, ElementType &gt;',['../structcvflann_1_1square_distance_3_01_chi_square_distance_3_01_element_type_01_4_00_01_element_type_01_4.html',1,'cvflann']]],
  ['squaredistance_3c_20hellingerdistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['squareDistance&lt; HellingerDistance&lt; ElementType &gt;, ElementType &gt;',['../structcvflann_1_1square_distance_3_01_hellinger_distance_3_01_element_type_01_4_00_01_element_type_01_4.html',1,'cvflann']]],
  ['squaredistance_3c_20l2_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['squareDistance&lt; L2&lt; ElementType &gt;, ElementType &gt;',['../structcvflann_1_1square_distance_3_01_l2_3_01_element_type_01_4_00_01_element_type_01_4.html',1,'cvflann']]],
  ['squaredistance_3c_20l2_5fsimple_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['squareDistance&lt; L2_Simple&lt; ElementType &gt;, ElementType &gt;',['../structcvflann_1_1square_distance_3_01_l2___simple_3_01_element_type_01_4_00_01_element_type_01_4.html',1,'cvflann']]],
  ['squaredistance_3c_20minkowskidistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['squareDistance&lt; MinkowskiDistance&lt; ElementType &gt;, ElementType &gt;',['../structcvflann_1_1square_distance_3_01_minkowski_distance_3_01_element_type_01_4_00_01_element_type_01_4.html',1,'cvflann']]],
  ['stabilizerbase',['StabilizerBase',['../classcv_1_1videostab_1_1_stabilizer_base.html',1,'cv::videostab']]],
  ['startstoptimer',['StartStopTimer',['../classcvflann_1_1_start_stop_timer.html',1,'cvflann']]],
  ['static',['Static',['../structcv_1_1gpu_1_1device_1_1_static.html',1,'cv::gpu::device']]],
  ['static_3c_20true_20_3e',['Static&lt; true &gt;',['../structcv_1_1gpu_1_1device_1_1_static_3_01true_01_4.html',1,'cv::gpu::device']]],
  ['staticasserttypeeqhelper',['StaticAssertTypeEqHelper',['../structtesting_1_1internal_1_1_static_assert_type_eq_helper.html',1,'testing::internal']]],
  ['staticasserttypeeqhelper_3c_20t_2c_20t_20_3e',['StaticAssertTypeEqHelper&lt; T, T &gt;',['../structtesting_1_1internal_1_1_static_assert_type_eq_helper_3_01_t_00_01_t_01_4.html',1,'testing::internal']]],
  ['staticif',['StaticIf',['../structcv_1_1gpu_1_1device_1_1reduce__detail_1_1_static_if.html',1,'cv::gpu::device::reduce_detail']]],
  ['staticif',['StaticIf',['../structcv_1_1gpu_1_1device_1_1reduce__key__val__detail_1_1_static_if.html',1,'cv::gpu::device::reduce_key_val_detail']]],
  ['staticif_3c_20false_2c_20t1_2c_20t2_20_3e',['StaticIf&lt; false, T1, T2 &gt;',['../structcv_1_1gpu_1_1device_1_1reduce__detail_1_1_static_if_3_01false_00_01_t1_00_01_t2_01_4.html',1,'cv::gpu::device::reduce_detail']]],
  ['staticif_3c_20false_2c_20t1_2c_20t2_20_3e',['StaticIf&lt; false, T1, T2 &gt;',['../structcv_1_1gpu_1_1device_1_1reduce__key__val__detail_1_1_static_if_3_01false_00_01_t1_00_01_t2_01_4.html',1,'cv::gpu::device::reduce_key_val_detail']]],
  ['staticif_3c_20true_2c_20t1_2c_20t2_20_3e',['StaticIf&lt; true, T1, T2 &gt;',['../structcv_1_1gpu_1_1device_1_1reduce__key__val__detail_1_1_static_if_3_01true_00_01_t1_00_01_t2_01_4.html',1,'cv::gpu::device::reduce_key_val_detail']]],
  ['staticif_3c_20true_2c_20t1_2c_20t2_20_3e',['StaticIf&lt; true, T1, T2 &gt;',['../structcv_1_1gpu_1_1device_1_1reduce__detail_1_1_static_if_3_01true_00_01_t1_00_01_t2_01_4.html',1,'cv::gpu::device::reduce_detail']]],
  ['stereobeliefpropagation',['StereoBeliefPropagation',['../classcv_1_1gpu_1_1_stereo_belief_propagation.html',1,'cv::gpu']]],
  ['stereobeliefpropagation',['StereoBeliefPropagation',['../classcv_1_1ocl_1_1_stereo_belief_propagation.html',1,'cv::ocl']]],
  ['stereobm_5fgpu',['StereoBM_GPU',['../classcv_1_1gpu_1_1_stereo_b_m___g_p_u.html',1,'cv::gpu']]],
  ['stereobm_5focl',['StereoBM_OCL',['../classcv_1_1ocl_1_1_stereo_b_m___o_c_l.html',1,'cv::ocl']]],
  ['stereoconstantspacebp',['StereoConstantSpaceBP',['../classcv_1_1ocl_1_1_stereo_constant_space_b_p.html',1,'cv::ocl']]],
  ['stereoconstantspacebp',['StereoConstantSpaceBP',['../classcv_1_1gpu_1_1_stereo_constant_space_b_p.html',1,'cv::gpu']]],
  ['stereographicprojector',['StereographicProjector',['../structcv_1_1detail_1_1_stereographic_projector.html',1,'cv::detail']]],
  ['stereographicwarper',['StereographicWarper',['../classcv_1_1_stereographic_warper.html',1,'cv']]],
  ['stereographicwarper',['StereographicWarper',['../classcv_1_1detail_1_1_stereographic_warper.html',1,'cv::detail']]],
  ['stitcher',['Stitcher',['../classcv_1_1_stitcher.html',1,'cv']]],
  ['stream',['Stream',['../classcv_1_1gpu_1_1_stream.html',1,'cv::gpu']]],
  ['streamaccessor',['StreamAccessor',['../structcv_1_1gpu_1_1_stream_accessor.html',1,'cv::gpu']]],
  ['string',['String',['../classtesting_1_1internal_1_1_string.html',1,'testing::internal']]],
  ['studentextraction',['StudentExtraction',['../class_student_extraction.html',1,'']]],
  ['studentlocalization',['StudentLocalization',['../class_student_localization.html',1,'']]],
  ['studentpreprocessing',['StudentPreProcessing',['../class_student_pre_processing.html',1,'']]],
  ['superresolution',['SuperResolution',['../classcv_1_1superres_1_1_super_resolution.html',1,'cv::superres']]],
  ['surf_5fgpu',['SURF_GPU',['../classcv_1_1gpu_1_1_s_u_r_f___g_p_u.html',1,'cv::gpu']]],
  ['surf_5focl',['SURF_OCL',['../classcv_1_1ocl_1_1_s_u_r_f___o_c_l.html',1,'cv::ocl']]],
  ['surffeaturesfinder',['SurfFeaturesFinder',['../classcv_1_1detail_1_1_surf_features_finder.html',1,'cv::detail']]]
];
